# Generated by Django 2.2.7 on 2019-11-19 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('path', models.CharField(max_length=2048)),
                ('ispretraining', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='ModelWeights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=2048)),
                ('default', models.CharField(max_length=50)),
                ('values', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['name'], name='backend_app_name_e0f10c_idx'),
        ),
        migrations.AddField(
            model_name='propertyinstance',
            name='modelweights_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_app.ModelWeights'),
        ),
        migrations.AddField(
            model_name='propertyinstance',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_app.Property'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['name'], name='backend_app_name_1b7edb_idx'),
        ),
        migrations.AddField(
            model_name='project',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_app.Task'),
        ),
        migrations.AddField(
            model_name='modelweights',
            name='finetuning_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finetuning_id', to='backend_app.Dataset'),
        ),
        migrations.AddField(
            model_name='modelweights',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_app.Model'),
        ),
        migrations.AddField(
            model_name='modelweights',
            name='pretraining_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pretraining_id', to='backend_app.Dataset'),
        ),
        migrations.AddField(
            model_name='modelweights',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_app.Task'),
        ),
        migrations.AddField(
            model_name='model',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_app.Task'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_app.Task'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name'], name='backend_app_name_39c44f_idx'),
        ),
        migrations.AddIndex(
            model_name='model',
            index=models.Index(fields=['name'], name='backend_app_name_9539ea_idx'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['name'], name='backend_app_name_aef2fc_idx'),
        ),
    ]
