# Generated by Django 2.2.7 on 2019-11-20 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_add_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelweights',
            options={'verbose_name_plural': 'Model weights'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='project',
            name='modelweights_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend_app.ModelWeights'),
        ),
    ]
