# Generated by Django 2.2.7 on 2019-11-26 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_add_fk_in_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='modelweights',
            options={'ordering': ['id'], 'verbose_name_plural': 'Model weights'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['id'], 'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertyinstance',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.AlterField(
            model_name='modelweights',
            name='finetuning_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finetuning_id', to='backend_app.Dataset'),
        ),
        migrations.AlterField(
            model_name='property',
            name='values',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
