# Generated by Django 2.2.7 on 2019-12-03 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_edit_property'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyInstance',
            new_name='TrainingSetting',
        ),
        migrations.RemoveField(
            model_name='modelweights',
            name='finetuning_id',
        ),
        migrations.RemoveField(
            model_name='modelweights',
            name='pretraining_id',
        ),
        migrations.AddField(
            model_name='modelweights',
            name='dataset_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='backend_app.Dataset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelweights',
            name='pretrained_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_app.ModelWeights'),
        ),
        migrations.CreateModel(
            name='AllowedProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_value', models.CharField(blank=True, max_length=200, null=True)),
                ('allowed_value', models.CharField(blank=True, max_length=200, null=True)),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.Model')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_app.Property')),
            ],
            options={
                'ordering': ['model_id'],
            },
        ),
    ]
