# Generated by Django 2.2.8 on 2019-12-12 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_add_inference_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingsetting',
            name='modelweights_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.ModelWeights'),
        ),
        migrations.AlterField(
            model_name='trainingsetting',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.Property'),
        ),
    ]
