# Generated by Django 2.2.8 on 2019-12-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_edit_trainingsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='inference',
            name='stats',
            field=models.CharField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
