# Generated by Django 2.2.8 on 2019-12-16 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0008_edit_inferencemodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allowedproperty',
            unique_together={('model_id', 'property_id')},
        ),
        migrations.AlterUniqueTogether(
            name='trainingsetting',
            unique_together={('modelweights_id', 'property_id')},
        ),
    ]
