# Generated by Django 2.2.9 on 2020-02-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0009_add_unique_together_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelweights',
            name='celery_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
