# Generated by Django 2.2.10 on 2020-02-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0010_add_celery_id_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inference',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='inference',
            name='celery_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='inference',
            index=models.Index(fields=['celery_id'], name='backend_app_celery__0439eb_idx'),
        ),
        migrations.AddIndex(
            model_name='modelweights',
            index=models.Index(fields=['celery_id'], name='backend_app_celery__bb94f6_idx'),
        ),
    ]
