# Generated by Django 3.0.3 on 2020-02-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0012_remove_ispretraining_dataset'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dataset',
            name='backend_app_name_aef2fc_idx',
        ),
        migrations.AddField(
            model_name='dataset',
            name='is_single_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['is_single_image'], name='backend_app_is_sing_fc3733_idx'),
        ),
    ]
