# Generated by Django 3.0.3 on 2020-03-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0014_add_logfile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='inference',
            name='outputfile',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
