# Generated by Django 3.0.4 on 2020-05-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0016_remove_task_id_ModelWeights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='default',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
