# Generated by Django 3.0.7 on 2020-07-17 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0017_optional_default_in_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_id', models.CharField(blank=True, max_length=50, null=True)),
                ('logfile', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'verbose_name_plural': 'Trainings',
            },
        ),
        migrations.AlterModelOptions(
            name='modelweights',
            options={'verbose_name_plural': 'Model Weights'},
        ),
        migrations.RemoveIndex(
            model_name='modelweights',
            name='backend_app_celery__bb94f6_idx',
        ),
        migrations.RemoveField(
            model_name='modelweights',
            name='celery_id',
        ),
        migrations.RemoveField(
            model_name='modelweights',
            name='logfile',
        ),
        migrations.AddField(
            model_name='modelweights',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='training',
            name='modelweights_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.ModelWeights'),
        ),
        migrations.AddField(
            model_name='training',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.Project'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['celery_id'], name='backend_app_celery__e53b96_idx'),
        ),
    ]
