# Generated by Django 3.0.7 on 2020-09-04 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend_app', '0020_add_dataset_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWeightsPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('VIEW', 'can view'), ('ADD', 'can add'), ('CHANGE', 'can change'), ('DELETE', 'can delete')], max_length=6)),
                ('modelweight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.ModelWeights')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='modelweights',
            name='owners',
            field=models.ManyToManyField(through='backend_app.ModelWeightsPermission', to=settings.AUTH_USER_MODEL),
        ),
    ]
