# Generated by Django 3.0.7 on 2020-09-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0022_edit_trainingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='celery_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
