# Generated by Django 3.0.7 on 2020-09-11 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0023_add_celery_id_to_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetpermission',
            name='permission',
            field=models.CharField(blank=True, choices=[('VIEW', 'can view'), ('ADD', 'can add'), ('CHANGE', 'can change'), ('DELETE', 'can delete')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='modelweights',
            name='dataset_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.Dataset'),
        ),
        migrations.AlterField(
            model_name='modelweights',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.Model'),
        ),
        migrations.AlterField(
            model_name='modelweightspermission',
            name='permission',
            field=models.CharField(blank=True, choices=[('VIEW', 'can view'), ('ADD', 'can add'), ('CHANGE', 'can change'), ('DELETE', 'can delete')], max_length=6, null=True),
        ),
    ]
