# Generated by Django 3.1.2 on 2020-11-03 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend_app', '0024_make_permission_field_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(blank=True, choices=[('VIEW', 'can view'), ('ADD', 'can add'), ('CHANGE', 'can change'), ('DELETE', 'can delete')], max_length=6, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        # migrations.AlterField(
        #     model_name='project',
        #     name='users',
        #     field=models.ManyToManyField(through='backend_app.ProjectPermission', to=settings.AUTH_USER_MODEL),
        # ),
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(through='backend_app.ProjectPermission', to=settings.AUTH_USER_MODEL),
        ),
    ]
