# Generated by Django 3.1.2 on 2020-11-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0025_edit_project_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetpermission',
            name='permission',
            field=models.CharField(blank=True, choices=[('OWN', 'Can change and delete'), ('VIEW', 'Can view')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='modelweightspermission',
            name='permission',
            field=models.CharField(blank=True, choices=[('OWN', 'Can change and delete'), ('VIEW', 'Can view')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='permission',
            field=models.CharField(blank=True, choices=[('OWN', 'Can change and delete'), ('VIEW', 'Can view')], max_length=6, null=True),
        ),
    ]
