# Generated by Django 3.1.2 on 2020-11-19 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend_app', '0026_edit_permission_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='projects', through='backend_app.ProjectPermission', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='permission',
            field=models.CharField(choices=[('OWN', 'Can change and delete'), ('VIEW', 'Can view')], default='VIEW', max_length=6),
        ),
    ]
