# Generated by Django 3.1.3 on 2021-01-07 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0029_change_allowedproperty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inference',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='inference',
            name='project_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend_app.project'),
            preserve_default=False,
        ),
    ]
