# Generated by Django 3.1.7 on 2021-03-30 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0031_add_ctypes_to_dataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='celery_id',
        ),
        migrations.RemoveField(
            model_name='model',
            name='location',
        ),
        migrations.AddField(
            model_name='modelweights',
            name='process_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modelweights',
            name='dataset_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_app.dataset'),
        ),
    ]
