# Generated by Django 3.1.7 on 2021-03-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0032_remove_location_from_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelweights',
            name='layer_to_remove',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
