# Generated by Django 3.1.7 on 2021-04-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0035_add_classes_to_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelweights',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
