# Generated by Django 3.1.7 on 2021-04-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0036_add_is_active_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelweights',
            name='classes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
