# Generated by Django 3.1.7 on 2021-05-25 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0038_add_models_help_text_and_property_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='inference',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 25, 15, 33, 51, 598257)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inference',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='training',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 25, 15, 34, 15, 878086)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
